### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by strixw0w** [OlMi1/indminer#1]
Hello,

was just wondering will this actually work?

will it get a hit to an actual wallet?

also when you get a hit, does the miner stop or does it save the address somewhere?

thank you

**Comment by OlMi1** [comment]
See from line 174 in [program.cs](https://github.com/OlMi1/indminer/blob/main/IndMiner/Program.cs), we are on github for a reason. Webhook to you will be sent containing the private key. It will also be saved to file.
