### ISSUE TITLE
miner

### ISSUE THREAD

**Issue by matsan1122** [OlMi1/indminer#3]
how big is the chance that i get a hit if i leave it open for 5 hours. and where will the hits file be created when i get a hit

**Comment by matsan1122** [comment]
and where can i put the webhook link

**Comment by OlMi1** [comment]
Please continue using issues after they are closed.
The hits file will be created in the same folder, please read the source code. It will ask for the webhook during the first one, if it is not already set.

**Comment by matsan1122** [comment]
sorry, im new to this. i see it in the code. but how can i download it so it works with the miner.

**Comment by matsan1122** [comment]
i have been running it for some hours now. what is the average time it takes to get a hit?

**Comment by OlMi1** [comment]
`2^150 / wallets in database / speed in w/s / 60 / 60 / 24` 
days

**Comment by matsan1122** [comment]
![Knipsel](https://user-images.githubusercontent.com/82448824/166153483-674909cf-ad72-4f6c-aa4c-2041f1af34ca.PNG)

**Comment by matsan1122** [comment]
this is the speed

**Comment by matsan1122** [comment]
i don't get what you mean with w/s

**Comment by OlMi1** [comment]
Wallets per second. It says that in the title bar.

**Comment by matsan1122** [comment]
so how much hours/days would it take with 50000 w/s

**Comment by OlMi1** [comment]
Use the formula above...

**Comment by matsan1122** [comment]
where cqan i see how much wallets there are in the database

**Comment by matsan1122** [comment]
nevermind

**Comment by DenyFX** [comment]
how i set up this things? iam a noob at this section

**Comment by OlMi1** [comment]
> how i set up this things? iam a noob at this section

Just download the latest release

**Comment by matsan1122** [comment]
where can i see how many wallets are in the database?

**Comment by matsan1122** [comment]
i have been mining for a week and i still haven't got a hit

**Comment by OlMi1** [comment]
that's because it's borderline impossible
![image](https://user-images.githubusercontent.com/64090338/167899033-1ec341b7-35e7-4ab8-a024-2c0fee505f2e.png)

**Comment by matsan1122** [comment]
oh, lol
