### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by S0L6** [OlMi1/indminer#4]
I use dotnet run then this error gets outputted:

C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Extensions.Logging.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Win32.Primitives, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "NBitcoin, Version=7.0.6.0, Culture=neutral, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "OpenHardwareMonitorLib". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.AppContext, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Collections.NonGeneric, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Console, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Diagnostics.DiagnosticSource, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Globalization.Calendars, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Globalization.Extensions, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.IO.Compression, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.IO.Compression.ZipFile, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.IO.FileSystem, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.IO.FileSystem.Primitives, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Net.NameResolution, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Net.Sockets, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Security.Cryptography.Csp, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Security.Cryptography.Encoding, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Security.Cryptography.Primitives, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Security.Cryptography.X509Certificates, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Threading.Thread, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Xml.ReaderWriter, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\Program.cs(2,7): error CS0246: The type or namespace name 'NBitcoin' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\Program.cs(146,23): error CS0246: The type or namespace name 'Key' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\Program.cs(159,40): error CS0246: The type or namespace name 'Key' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\Program.cs(164,40): error CS0246: The type or namespace name 'Key' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\Program.cs(169,44): error CS0246: The type or namespace name 'Key' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\Program.cs(174,41): error CS0246: The type or namespace name 'Key' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]

I think there might be something missing (I am new to c#)

**Comment by OlMi1** [comment]
Please install nBitcoin via nuget. Also make sure all build actions are removed (Edit -> Project -> Build Events, both big text fields should be empty).

**Comment by S0L6** [comment]
Where do I edit build actions?

**Comment by S0L6** [comment]
New error
PM> dotnet run --project IndMiner
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(5706,5): error MSB3073: The command "REM Eazfuscator.NET is integrated with this project at MSBuild level: https://www.gapotchenko.com/eazfuscator.net/kb/100036 [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
C:\Program Files\dotnet\sdk\6.0.202\Microsoft.Common.CurrentVersion.targets(5706,5): error MSB3073: "C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\signtool.exe" sign /a C:\Users\olemi\source\repos\IndMiner\IndMiner\bin\Release\IndMiner.exe" exited with code 3. [C:\Users\bugs0\Documents\GitHub\walletminer\IndMiner\IndMiner.csproj]
dotnet : 
At line:1 char:1
+ dotnet run --project IndMiner
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
The build failed. Fix the build errors and run again.

**Comment by OlMi1** [comment]
You need to clear build actions.

**Comment by OlMi1** [comment]
Issue may be reopened at any time but seems like the problem has a solution written in the readme
