### ISSUE TITLE
sorry but i dont know how to use it 

### ISSUE THREAD

**Issue by N01ZH** [OlMi1/indminer#5]
it seems like you have it connected to a discord bot and so on... do i need to read somthing before doing all this or am i just dump???:)

**Comment by OlMi1** [comment]
Please read the readme for setup information. You CAN connect a discord webhook or just not enter it. Your choice. 

https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks

Please do not open issues for stuff that‘s in the readme or may have already been answered by closed issues.

**Comment by N01ZH** [comment]
tnx for a fast answer
